=== zsofiaviola/LFM4UL_XMLgyak/LFM4UL_1013/SZZSV_konyv1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="konyvek">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="konyv" type="konyvTipus" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="konyvTipus">
		<xs:sequence>
			<xs:element name="cim" type="xs:string"/>
			<xs:element name="szerzo" type="xs:string"/>
			<xs:element name="szereplo" type="szereploTipus"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="szereploTipus">
		<xs:sequence>
			<xs:element name="nev" type="xs:string"/>
			<xs:element name="barat" type="xs:string"/>
			<xs:element name="szuletett" type="xs:int"/>
			<xs:element name="jellemzes" type="xs:string"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:int" use="required"/>
	</xs:complexType>
	
	


</xs:schema>

=== zsofiaviola/LFM4UL_XMLgyak/LFM4UL_1013/SZZSV_konyv1.xml
<?xml version="1.0" encoding="UTF-8"?>

<konyvek xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="SZZSV_konyv1.xsd">
	<konyv>
		<cim>Langolierek-Az ido fogsagaban</cim>
		<szerzo>Stephen King</szerzo>
		<szereplo id="01">
			<nev>Patricia Wettig</nev>
			<barat>Ken Olin</barat>
			<szuletett>1951.12.04.</szuletett>
			<jellemzes>kedves</jellemzes>
		</szereplo>
		
		<szereplo id="02">
			<nev>Mark Lindsay Chapman</nev>
			<szuletett>1954.09.08.</szuletett>
			<jellemzes>jofej</jellemzes>
		</szereplo>

	</konyv>
</konyvek>
