=== zsofiaviola/LFM4UL_XMLgyak/XMLTaskLFM4UL/XMLSchemaLFM4UL.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="qualified">
    <xs:element name="koromlakkgyarto">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="gyarto" type="gyartoTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="koromlakkok" type="koromlakkokTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="rendel" type="rendelTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="vasarlo" type="vasarloTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="kiegeszitok" type="kiegeszitokTipus" minOccurs="0" maxOccurs="unbounded"/>
                <xs:element name="ajandek" type="ajandekTipus" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
     <xs:complexType name="gyartoTipus">
        <xs:sequence>
        	<xs:element name="nev" type="xs:string"/>
        	<xs:element name="informacio" type="informacioTipus"/>
        </xs:sequence>
    </xs:complexType>
    
     <xs:complexType name="informacioTipus">
        <xs:sequence>
            <xs:element name="telefonszam" type="xs:positiveInteger"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
     <xs:complexType name="koromlakkokTipus">
        <xs:sequence>
            <xs:element name="ar" type="xs:double"/>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="szin" type="xs:string"/>
            <xs:element name="tipus" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:integer"/>
    </xs:complexType>
    
    <xs:complexType name="rendelTipus">
        <xs:sequence>
            <xs:element name="datum" type="xs:date"/>
            <xs:element name="darabszam" type="xs:integer"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:integer"/>
    </xs:complexType>
    
    <xs:complexType name="vasarloTipus">
        <xs:sequence>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="elerhetoseg" type="elerhetosegTipus"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:integer"/>
    </xs:complexType>

    <xs:complexType name="elerhetosegTipus">
        <xs:sequence>
            <xs:element name="lakcim" type="lakcimTipus"/>
            <xs:element name="telefonszam" type="xs:positiveInteger"/>
            <xs:element name="email" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="lakcimTipus">
        <xs:sequence>
            <xs:element name="iranyitoszam" type="xs:integer"/>
            <xs:element name="varos" type="xs:string"/>
            <xs:element name="utca" type="xs:string"/>
            <xs:element name="hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
     <xs:complexType name="kiegeszitokTipus">
        <xs:sequence>
            <xs:element name="ar" type="xs:double"/>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="szin" type="xs:string"/>
            <xs:element name="tipus" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:integer"/>
    </xs:complexType>
    
     <xs:complexType name="ajandekTipus">
        <xs:sequence>
            <xs:element name="ar" type="xs:double"/>
            <xs:element name="nev" type="xs:string"/>
            <xs:element name="szin" type="xs:string"/>
            <xs:element name="tipus" type="xs:string" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="ID" type="xs:integer"/>
    </xs:complexType>
    
 
 
 </xs:schema>

=== zsofiaviola/LFM4UL_XMLgyak/XMLTaskLFM4UL/xmlLFM4UL.xml
<?xml version="1.0" encoding="utf-8" ?>

<koromlakkgyarto xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:noNamespaceSchemaLocation="XMLSchemaLFM4UL.xsd">
<gyarto>
	<nev>CandyNails</nev>
	<informacio>
		<telefonszam>06309876543</telefonszam>
		<email>candynails@gmail.com</email>
	</informacio>
</gyarto>
<koromlakkok ID="1234">
        <ar>2600</ar>
        <nev>Magnet Illusion</nev>
        <szin>marvany</szin>
        <tipus>magneses koromlakk</tipus>
</koromlakkok>
<koromlakkok ID="1235">
        <ar>2400</ar>
        <nev>Digital Illusion</nev>
        <szin>feher</szin>
        <tipus>csillogos koromlakk</tipus>
</koromlakkok>
<rendel ID="011">
        <datum>2021-11-20</datum>
        <darabszam>2</darabszam>
</rendel>
<vasarlo ID="111">
        <nev>Kiss Anna</nev>
        <elerhetoseg>
	        <lakcim>
	            <iranyitoszam>3423</iranyitoszam>
	            <varos>Tibolddaroc</varos>
	            <utca>Kacsi</utca>
	            <hazszam>11</hazszam>
	        </lakcim>
	        <telefonszam>06301234567</telefonszam>
	        <email>kissanna@gmail.com</email>
        </elerhetoseg>
</vasarlo>
<vasarlo ID="222">
        <nev>Nagy Niki</nev>
        <elerhetoseg>
	        <lakcim>
	            <iranyitoszam>3423</iranyitoszam>
	            <varos>Tibolddaroc</varos>
	            <utca>Abranyi</utca>
	            <hazszam>45</hazszam>
	        </lakcim>
	        <telefonszam>06301237863</telefonszam>
	        <email>nagyniki@gmail.com</email>
        </elerhetoseg>
</vasarlo>
<kiegeszitok ID="2345">
        <ar>1600</ar>
        <nev>magnes</nev>
        <szin>fekete</szin>
        <tipus>magnes</tipus>
</kiegeszitok>
<kiegeszitok ID="2346">
        <ar>2000</ar>
        <nev>matricak</nev>
        <szin>mindenfele</szin>
        <tipus>matrica</tipus>
</kiegeszitok>
<ajandek ID="26">
        <ar>0</ar>
        <nev>Sprarkling Crystals</nev>
        <szin>szinvalto</szin>
        <tipus>csillam</tipus>
</ajandek>
<ajandek ID="27">
        <ar>0</ar>
        <nev>Koromdiszito kovek</nev>
        <szin>kek</szin>
        <tipus>diszkovek</tipus>
</ajandek> 
</koromlakkgyarto>
