=== zsofiaviola/LFM4UL_XMLgyak/LMF4UL_1006/SZZSV_ertoxsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/SZZSV_ertoxsd" xmlns:tns="http://www.example.org/SZZSV_ertoxsd" elementFormDefault="qualified">
	<element name="modell">
		<complexType>
			<sequence>
				<element name="A" maxOccurs="unbounded">
					<complexType mixed="true">
						<sequence>
							<element name="b" type="string" />
							<element name="c" type="string" />
						</sequence>
						<attribute name="a1" type="int"/>
					</complexType>
				</element>
				
				<element name="B" maxOccurs="unbounded">
					<complexType mixed="true">
						<sequence>
							<element name="b" type="string" />
						</sequence>
						<attribute name="a1" type="int"/>
					</complexType>
				</element>
				
				<element name="C" maxOccurs="unbounded">
					<complexType mixed="true">
						<sequence>
							<element name="b" type="string" />
						</sequence>
						<attribute name="a1" type="int"/>
					</complexType>
				</element>
				
				<element name="AC" maxOccurs="unbounded">
					<complexType mixed="true">
						<sequence>
							<element name="ac1" type="string" />
							<element name="ac2" type="string" />
						</sequence>
					</complexType>
				</element>
				
				
				
			</sequence>
		</complexType>
	</element>




</schema>

=== zsofiaviola/LFM4UL_XMLgyak/LMF4UL_1006/SZZSV_xsdtoxml.xml
<?xml version="1.0" encoding="UTF-8"?>

<modell>
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="SZZSV_ertoxsd.xsd">
  <A a1="01">
    <b>string</b>
    <c>string</c>
  </A>
  <B a1="02">
    <b>string</b>
  </B>
  <C a1="03">
    <b>string</b>
  </C>
  <AC>
    <ac1>string</ac1>
    <ac2>string</ac2>
  </AC>
</modell>
